services:
  db:
    image: mysql:8.0    # Você pode especificar uma versão específica do MySQL aqui
    container_name: mysql_container2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: invoicing
      MYSQL_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my_network
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - my_network
    restart: always
volumes:
  db_data:
networks:
  my_network:
    driver: bridge
